version: '3.8'

services:
  app:
    container_name: pesantren-api
    image: pesantren-be:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./.env:/app/.env
    environment:
      - PORT=${PORT:-5000}
    networks:
      - pesantren-network

networks:
  pesantren-network:
    driver: bridge
