version: '3.8'

services:
  app:
    container_name: pesantren-api
    image: pesantren-be:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - '127.0.0.1:${PORT}:${PORT}'
    volumes:
      - ./.env:/app/.env
      - ./public:/app/public
    environment:
      - PORT=${PORT:-5000}
    networks:
      - pesantren-network

networks:
  pesantren-network:
    external: true
